version: 2.1

jobs:
  test:
    resource_class: small
    docker:
      - image: python:3.8-slim-buster
        environment:
          DATABASE_URL: postgresql://test:test@localhost:5432/test
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get -y install build-essential
            pip install pipenv
            pipenv install --dev
      - run:
          name: format-check
          command: pipenv run format-check
      - run:
          name: Run lint
          command: pipenv run lint
      - run:
          name: Migrate test db
          command: pipenv run alembic upgrade head
      - run:
          name: Run pytest
          command: pipenv run pytest
      
  build_deploy:
    resource_class: small
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t ${GOOGLE_CONTAINER_REGISTRY}/${GOOGLE_PROJECT}/${CIRCLE_PROJECT_REPONAME} --build-arg DATABASE_PASSWORD=${TF_VAR_forests_db_password} .
      - run:
          name: Activate Service Account
          command: |
            echo $GOOGLE_CREDENTIALS > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run:
          name: Deploy to Google Container Registry
          command: |
            gcloud auth configure-docker --quiet
            docker push ${GOOGLE_CONTAINER_REGISTRY}/${GOOGLE_PROJECT}/${CIRCLE_PROJECT_REPONAME}


workflows:
  build:
    jobs:
      - test:
          filters:
              branches:
                ignore: master
      - build_deploy:
          context: INFRASTRUCTURE
          filters:
            branches:
              only: master
