"""add_thumbnail_to_forests_model

Revision ID: 25c93d1c16be
Revises: 6e8e446bcaa2
Create Date: 2021-06-14 16:04:08.749212

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "25c93d1c16be"
down_revision = "6e8e446bcaa2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("forests", sa.Column("thumbnail", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("forests", "thumbnail")
    # ### end Alembic commands ###
