"""add_cover_to_forests_model

Revision ID: 4aadbe334df1
Revises: cc4b0ee439b6
Create Date: 2021-06-14 19:18:40.895574

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4aadbe334df1"
down_revision = "cc4b0ee439b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("forests", sa.Column("cover", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("forests", "cover")
    # ### end Alembic commands ###
