"""add_more_columns_to_forests_model

Revision ID: cc4b0ee439b6
Revises: 25c93d1c16be
Create Date: 2021-06-14 19:02:28.135584

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "cc4b0ee439b6"
down_revision = "25c93d1c16be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("forests", sa.Column("country", sa.String(), nullable=False))
    op.add_column("forests", sa.Column("latitude", sa.Integer(), nullable=False))
    op.add_column("forests", sa.Column("longitude", sa.Integer(), nullable=False))
    op.add_column("forests", sa.Column("area", sa.Integer(), nullable=False))
    op.add_column("forests", sa.Column("long_description", sa.String(), nullable=False))
    op.add_column("forests", sa.Column("carbon_stored", sa.Integer(), nullable=False))
    op.add_column(
        "forests", sa.Column("carbon_stored_delta", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("forests", "carbon_stored_delta")
    op.drop_column("forests", "carbon_stored")
    op.drop_column("forests", "long_description")
    op.drop_column("forests", "area")
    op.drop_column("forests", "longitude")
    op.drop_column("forests", "latitude")
    op.drop_column("forests", "country")
    # ### end Alembic commands ###
